name: status_download
description: A new Flutter application.
version: 6.0.0+6
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chewie: ^0.9.7
  thumbnails: ^1.0.1
  cupertino_icons: ^0.1.2
  path_provider: ^0.5.0+1
  flutter_staggered_grid_view:
  path:
  flutter_launcher_icons: ^0.7.0
  firebase_core: ^0.4.0+1
  firebase_admob: ^0.5.2
  url_launcher: ^5.0.2
  share: ^0.6.1+1
  simple_permissions: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/avatar.png
    - assets/images/video_loader.gif